name: Tools & SDK

on:
  push:
    branches: [ 'main' ]

jobs:
  docker-images:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    outputs:
      image: ${{ steps.meta.tags }}

    steps:
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: GHCR Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - uses: docker/bake-action@v2
        with:
          push: true
          pull: true
          targets: |
            sdk
            rkdeveloptool
          set: |
            *.cache-from=type=gha,mode=max
            *.cache-to=type=gha,mode=max
            sdk.platform=linux/amd64,linux/arm64
            rkdeveloptool.platform=linux/amd64,linux/arm64
