name: Tools & SDK

on:
  push:
    branches: [ 'main' ]

jobs:
  docker-images:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    outputs:
      image: ${{ steps.meta.tags }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: docker.io/${{ github.actor }}/rock5b-sdk
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          pull: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: sdk
          platforms: linux/amd64
          build-contexts: |
            git-rkbin=https://github.com/radxa/rkbin.git#master
            git-radxa-build=https://github.com/radxa/build.git#debian
