name: Rockchip MPP

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - 'rkmpp/**'
  schedule:
    - cron: '15 18 * * 5' # 18:15 UTC on Friday

jobs:
  images:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - os: 'ubuntu'
            version: '20.04'
          - os: 'ubuntu'
            version: '22.04'
          - os: 'debian'
            version: 'bullseye'

    outputs:
      image: ${{ steps.meta.tags }}

    steps:
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: milas
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: GHCR Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: docker.io/milas/rkmpp-${{ matrix.os }}
          tags: |
            type=ref,event=branch,prefix=${{ matrix.version }}-
            type=raw,value=${{ matrix.version }},enable={{is_default_branch}}

      - uses: docker/build-push-action@v3
        with:
          push: true
          pull: true
          provenance: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64
          context: "{{defaultContext}}:rkmpp"
          target: os
          build-args: |
            OS_BASE=docker.io/${{ matrix.os }}:${{ matrix.version }}
