name: SDK

on:
  push:
    branches: [main]
    paths-ignore:
      - 'rkmpp/**'
      - 'rknn/**'

jobs:
  images:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    outputs:
      image: ${{ steps.meta.tags }}

    steps:
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: milas
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: GHCR Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: SDK Meta
        id: sdk_meta
        uses: docker/metadata-action@v4
        with:
          images: docker.io/milas/rock5-sdk
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: SDK Image
        uses: docker/build-push-action@v3
        with:
          push: true
          pull: true
          tags: ${{ steps.sdk_meta.outputs.tags }}
          labels: ${{ steps.sdk_meta.outputs.labels }}
          target: sdk
          platforms: linux/amd64,linux/arm64
          provenance: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: rkdeveloptool Meta
        id: rkdeveloptool_meta
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/milas/rkdeveloptool
            ghcr.io/milas/rkdeveloptool
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: rkdeveloptool Image
        uses: docker/build-push-action@v3
        with:
          push: true
          pull: true
          tags: ${{ steps.rkdeveloptool_meta.outputs.tags }}
          labels: ${{ steps.rkdeveloptool_meta.outputs.labels }}
          target: rkdeveloptool
          platforms: linux/amd64,linux/arm64
          provenance: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
