name: U-Boot

on:
  workflow_dispatch: {}
  push:
    branches: [main, self-hosted-testing]
  schedule:
    - cron: '15 18 * * 2' # 18:15 UTC on Tuesday

jobs:
  u-boot:
    runs-on: self-hosted

    strategy:
      matrix:
        board: [rock-5a, rock-5b]
        variant: [radxa, collabora]
        exclude:
          - board: rock-5a
            variant: collabora
        include:
          - board: rock-5a
            chip: rk3588s
          - board: rock-5b
            chip: rk3588

    permissions:
      contents: read
      packages: none

    steps:
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: docker.io/${{ github.actor }}/rock5-u-boot
          flavor: suffix=-${{ matrix.board }}-${{ matrix.variant }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=schedule,pattern=latest
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=u-boot/${{ matrix.board }}/${{ matrix.variant }}
            org.opencontainers.image.description=U-Boot bootloader for Rock 5

      - uses: docker/build-push-action@v3
        with:
          push: true
          pull: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: u-boot-${{ matrix.variant }}
          build-args: |
            CHIP=${{ matrix.chip }}
            BOARD=${{ matrix.board }}
          platforms: linux/arm64
          provenance: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
